# Configuration for Extras plugin
allowJoinOnFullServer: true
enableKick: false
enableJoinRestrictions: false
opOnJoin: true
# It's recommended to do this on a pre-generated world
# as chunk generation can be very slow in newer Minecraft
# versions.
# You can use the pre-world generation plugin "Chunky" to achieve this.
randomizeSpawn: false
maxEntitiesPerChunk: 50
maxEntitiesPerWorld: 5120
maxTntsPerWorld: 1024
playerJoinTitle: "§7Welcome to Kaboom!"
playerJoinSubtitle: "Free OP • Anarchy • Creative"
opTag: "§4§l[§c§lOP§4§l] §c"
deOpTag: "§8§l[§7§lDeOP§8§l] §7"
